query MangaList(
  $page: Int
  $perPage: Int
  $search: String
  $sort: [MediaSort]
  $status: MediaStatus
  $format: MediaFormat
  $genre: String
) {
  Page(page: $page, perPage: $perPage) {
    media(
      type: MANGA
      search: $search
      sort: $sort
      isAdult: false
      status: $status
      format: $format
      genre: $genre
    ) {
      id
      idMal
      type
      format
      countryOfOrigin
      status
      meanScore
      bannerImage
      description
      startDate {
        year
      }
      coverImage {
        large
      }
      title {
        romaji
        english
        native
      }
    }
  }
}